name: CI
on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust: [stable, beta, nightly]
    steps:
    - uses: actions/checkout@master
    - name: Install Rust
      run: rustup update ${{ matrix.rust }} && rustup default ${{ matrix.rust }}
    - run: cargo build --all
    - run: cargo test --all
    - run: cargo build --all --features=alloc
    - run: cargo test --all --features=alloc
    - run: cargo build --all --features=std
    - run: cargo test --all --features=std
    - run: cargo build --all --features=alloc,std
    - run: cargo test --all --features=alloc,std

  test-old:
    name: Test on old releases of Rust
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust: [1.31.1]
    steps:
    - uses: actions/checkout@master
    - name: Install Rust
      run: rustup update ${{ matrix.rust }} && rustup default ${{ matrix.rust }}
    - run: cargo build --all
    - run: cargo test --all
    - run: cargo build --all --features=std
    - run: cargo test --all --features=std

  rustfmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install Rust
      run: rustup update stable && rustup default stable && rustup component add rustfmt
    - run: cargo fmt -- --check

  publish_docs:
    name: Publish Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install Rust
        run: rustup update stable && rustup default stable
      - name: Build documentation
        run: cargo doc --no-deps --features alloc
      - name: Publish documentation
        run: |
          cd target/doc
          git init
          git add .
          git -c user.name='ci' -c user.email='ci' commit -m init
          git push -f -q https://git:${{ secrets.github_token }}@github.com/${{ github.repository }} HEAD:gh-pages
        if: github.event_name == 'push' && github.event.ref == 'refs/heads/master'
